name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  RunTests:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: tendermintdev/docker-tm-db-testing
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: go test ./... -mod=readonly -timeout 8m -race -tags=memdb,goleveldb,cleveldb,rocksdb -v

