name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  Test:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v3
      - name: test & coverage report creation
        run: |
          pacman -Syyu go base-devel rocksdb leveldb
          go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic -tags=memdb,goleveldb,cleveldb,rocksdb -v

