name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: |
          pacman -Syyu --noconfirm go base-devel rocksdb leveldb
          go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic -tags=memdb,goleveldb,cleveldb,rocksdb -v
